
-- Letters NOT appearing in the first position of Code
SELECT char
FROM (
  SELECT substr('ABCDEFGHIJKLMNOPQRSTUVWXYZ', n, 1) AS char
  FROM (
    SELECT 1 AS n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5
    UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
    UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
    UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
    UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25
    UNION SELECT 26
  )
)
WHERE char NOT IN (
  SELECT DISTINCT SUBSTR(Code, 1, 1)
  FROM Country
  WHERE LENGTH(Code) = 3
);

-- Letters NOT appearing in the second position of Code
SELECT char
FROM (
  SELECT substr('ABCDEFGHIJKLMNOPQRSTUVWXYZ', n, 1) AS char
  FROM (
    SELECT 1 AS n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5
    UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
    UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
    UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
    UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25
    UNION SELECT 26
  )
)
WHERE char NOT IN (
  SELECT DISTINCT SUBSTR(Code, 2, 1)
  FROM Country
  WHERE LENGTH(Code) = 3
);

-- Letters NOT appearing in the third position of Code
SELECT char
FROM (
  SELECT substr('ABCDEFGHIJKLMNOPQRSTUVWXYZ', n, 1) AS char
  FROM (
    SELECT 1 AS n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5
    UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
    UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
    UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
    UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25
    UNION SELECT 26
  )
)
WHERE char NOT IN (
  SELECT DISTINCT SUBSTR(Code, 3, 1)
  FROM Country
  WHERE LENGTH(Code) = 3
);
